[package]
name = "ubi"
version = "0.1.0"
edition = "2021"

[dependencies]
gl = '*'
sdl2 = { version = '*', features = ["bundled"]}
image = "0.24"
log = "0.4.27"
env_logger = "0.11.8"
thiserror = "2.0.12"
bitflags = "2.4"
egui = "0.31"
egui_sdl2_gl = "0.31"
